AllCops:
  NewCops: enable
  Exclude:
    - 'app/lib/active_record_extender/active_record_extender.rb'
    - 'app/models/concerns/active_record_extensions.rb'
    - 'bin/**/*'
    - 'db/**/*'
    - 'db/schema.rb'
    - 'config/application.rb'
    - 'config/routes.rb'
    - 'config/puma.rb'
    - 'config/puma/**/*'
    - 'config/spring.rb'
    - 'config/initializers/airbrake.rb'
    - 'config/initializers/wrap_parameters.rb'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/environments/development.rb'
    - 'config/environments/test.rb'
    - 'config/environments/production.rb'
    - 'config/environments/sample_development.rb'
    - 'config/environments/sample_test.rb'
    - 'config/environments/sample_production.rb'
    - 'Guardfile'
    - 'lib/generators/request_spec/request_spec_generator.rb'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'Rakefile'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/**/*'
    - 'test/**/*'
    - 'vendor/**/*.rb'
    - 'vendor/bundle/**/*'
Layout/LineLength:
  Max: 90
  Exclude:
  - 'spec/**/*.rb'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Metrics/ClassLength:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/CollectionCompact:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
Layout/MultilineMethodCallIndentation:
  Enabled: false